// AccessControl Specification - ShadowFi
// Hack: ShadowFi
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: ShadowFi
// PRIVILEGED FUNCTION: burn
//

methods {
    // --- Privileged functions ---
    function burn(address, uint256) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call burn ---
rule onlyOwnerCanCall_burn(env e, address addr, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    burn@withrevert(e, addr, amount);
    assert lastReverted, "Unprivileged caller should not be able to call burn";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
