// AccessControl Specification - StaxLPStaking
// Hack: Templedao
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: StaxLPStaking
// PRIVILEGED FUNCTION: withdraw
//

methods {
    // --- Privileged functions ---
    function withdraw(uint256, bool) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call withdraw ---
rule onlyOwnerCanCall_withdraw(env e, uint256 amount, bool flag) {
    require e.msg.sender != currentContract.owner();
    withdraw@withrevert(e, amount, flag);
    assert lastReverted, "Unprivileged caller should not be able to call withdraw";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
