// AccessControl Specification - unverified_8490
// Auto-generated by build_ac_dataset_defihacks.py
// 2026-05-12 17:11 UTC
//
// INSTRUCTIONS:
//   1. Replace <ContractName> with the real vulnerable contract name
//   2. Replace <privileged_function> with the unprotected function identified
//   3. Adjust the methods block according to the real ABI
//

methods {
    // --- Privileged functions (examples - adapt) ---
    function <privileged_function>() external;
    function owner() external returns (address) envfree;
    // --- Proxy ---
    function upgradeTo(address) external;
    function implementation() external returns (address) envfree;
}

// --- Rule: only owner can call privileged functions ---
rule onlyOwnerCanCallPrivileged(env e) {
    require e.msg.sender != currentContract.owner();
    <privileged_function>@withrevert(e);
    assert lastReverted, "Unprivileged caller should be rejected";
}

// --- Rules specific to Proxy contracts ---
rule onlyAuthorizedCanUpgrade(env e, address newImpl) {
    require e.msg.sender != currentContract.owner();
    upgradeTo@withrevert(e, newImpl);
    assert lastReverted, "Only owner should upgrade implementation";
}

invariant implementationNeverZero()
    implementation() != 0
    { preserved { require implementation() != 0; } }

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
