// AccessControl Specification - BorrowerOperationsV6
// Hack: TokenHolder
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: BorrowerOperationsV6
// PRIVILEGED FUNCTION: initialize
//

methods {
    // --- Privileged functions ---
    function initialize(IERC20) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call initialize ---
rule onlyOwnerCanCall_initialize(env e, IERC20 val) {
    require e.msg.sender != currentContract.owner();
    initialize@withrevert(e, val);
    assert lastReverted, "Unprivileged caller should not be able to call initialize";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
