// AccessControl Specification - LeverageUp
// Hack: SizeCredit
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: LeverageUp
// PRIVILEGED FUNCTION: validateInitialize
//

methods {
    // --- Privileged functions ---
    function validateInitialize(address token, uint256 amount) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call validateInitialize ---
rule onlyOwnerCanCall_validateInitialize(env e, address addr, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    validateInitialize@withrevert(e, addr, amount);
    assert lastReverted, "Unprivileged caller should not be able to call validateInitialize";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
