// AccessControl Specification - LinearVesting
// Hack: FILX_DN404
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: LinearVesting
// PRIVILEGED FUNCTION: init
//

methods {
    // --- Privileged functions ---
    function init(IERC20, uint256, uint256) external;
    function owner() external returns (address) envfree;
    function upgradeTo(address newImpl) external;
    function implementation() external returns (address) envfree;
}

// --- Rule: only owner can call init ---
rule onlyOwnerCanCall_init(env e, IERC20 val, uint256 amount, uint256 amount1) {
    require e.msg.sender != currentContract.owner();
    init@withrevert(e, val, amount, amount1);
    assert lastReverted, "Unprivileged caller should not be able to call init";
}

// --- Rule: only owner can upgrade implementation ---
rule onlyOwnerCanUpgrade(env e, address newImpl) {
    require e.msg.sender != currentContract.owner();
    upgradeTo@withrevert(e, newImpl);
    assert lastReverted, "Only owner should upgrade implementation";
}

invariant implementationNeverZero()
    implementation() != 0
    { preserved { require implementation() != 0; } }

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
