// AccessControl Specification - RareStakingV1
// Hack: SuperRare
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: RareStakingV1
// PRIVILEGED FUNCTION: initialize
//

methods {
    // --- Privileged functions ---
    function initialize(address, bytes32, address) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call initialize ---
rule onlyOwnerCanCall_initialize(env e, address addr, bytes32 role, address addr1) {
    require e.msg.sender != currentContract.owner();
    initialize@withrevert(e, addr, role, addr1);
    assert lastReverted, "Unprivileged caller should not be able to call initialize";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
