// AccessControl Specification - GymRouter
// Hack: GYMNetwork
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: GymRouter
// PRIVILEGED FUNCTION: initialize
//

methods {
    // --- Privileged functions ---
    function initialize(address, address, uint256) external;
    function owner() external returns (address) envfree;
    function upgradeTo(address newImpl) external;
    function implementation() external returns (address) envfree;
}

// --- Rule: only owner can call initialize ---
rule onlyOwnerCanCall_initialize(env e, address addr, address addr1, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    initialize@withrevert(e, addr, addr1, amount);
    assert lastReverted, "Unprivileged caller should not be able to call initialize";
}

// --- Rule: only owner can upgrade implementation ---
rule onlyOwnerCanUpgrade(env e, address newImpl) {
    require e.msg.sender != currentContract.owner();
    upgradeTo@withrevert(e, newImpl);
    assert lastReverted, "Only owner should upgrade implementation";
}

invariant implementationNeverZero()
    implementation() != 0
    { preserved { require implementation() != 0; } }

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
