// AccessControl Specification - BEP20TokenImplementation
// Hack: Rikkei_Finance
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: BEP20TokenImplementation
// PRIVILEGED FUNCTION: transfer
//

methods {
    // --- Privileged functions ---
    function transfer(address, uint256) external;
    function owner() external returns (address) envfree;
    function upgradeTo(address newImpl) external;
    function implementation() external returns (address) envfree;
}

// --- Rule: only owner can call transfer ---
rule onlyOwnerCanCall_transfer(env e, address addr, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    transfer@withrevert(e, addr, amount);
    assert lastReverted, "Unprivileged caller should not be able to call transfer";
}

// --- Rule: only owner can upgrade implementation ---
rule onlyOwnerCanUpgrade(env e, address newImpl) {
    require e.msg.sender != currentContract.owner();
    upgradeTo@withrevert(e, newImpl);
    assert lastReverted, "Only owner should upgrade implementation";
}

invariant implementationNeverZero()
    implementation() != 0
    { preserved { require implementation() != 0; } }

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
