// AccessControl Specification - cERC20
// Hack: Melo
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: cERC20
// PRIVILEGED FUNCTION: mint
//

methods {
    // --- Privileged functions ---
    function mint(address, uint256, string) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call mint ---
rule onlyOwnerCanCall_mint(env e, address addr, uint256 amount, string val) {
    require e.msg.sender != currentContract.owner();
    mint@withrevert(e, addr, amount, val);
    assert lastReverted, "Unprivileged caller should not be able to call mint";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
