// AccessControl Specification - PancakePair
// Hack: BRAND
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: PancakePair
// PRIVILEGED FUNCTION: transfer
//

methods {
    // --- Privileged functions ---
    function transfer(address, uint) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call transfer ---
rule onlyOwnerCanCall_transfer(env e, address addr, uint amount) {
    require e.msg.sender != currentContract.owner();
    transfer@withrevert(e, addr, amount);
    assert lastReverted, "Unprivileged caller should not be able to call transfer";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
