// AccessControl Specification - Stead
// Auto-generated by build_ac_dataset_defihacks.py
// 2026-05-12 17:11 UTC
//
// INSTRUCTIONS:
//   1. Replace TransparentUpgradeableProxy with the real vulnerable contract name
//   2. Replace owner with the unprotected function identified
//   3. Adjust the methods block according to the real ABI
//

methods {
    // --- Privileged functions (examples - adapt) ---
    function owner() external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call privileged functions ---
rule onlyOwnerCanCallPrivileged(env e) {
    require e.msg.sender != currentContract.owner();
    owner@withrevert(e);
    assert lastReverted, "Unprivileged caller should be rejected";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
