// AccessControl Specification - ERC677InitializableTokenV2
// Hack: INUMI_db27
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: ERC677InitializableTokenV2
// PRIVILEGED FUNCTION: burn
//

methods {
    // --- Privileged functions ---
    function burn(uint256) external;
    function owner() external envfree;
    function upgradeTo(address newImpl) external;
    function implementation() external returns (address) envfree;
}

// --- Rule: only owner can call burn ---
rule onlyOwnerCanCall_burn(env e, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    burn@withrevert(e, amount);
    assert lastReverted, "Unprivileged caller should not be able to call burn";
}

// --- Rule: only owner can upgrade implementation ---
rule onlyOwnerCanUpgrade(env e, address newImpl) {
    require e.msg.sender != currentContract.owner();
    upgradeTo@withrevert(e, newImpl);
    assert lastReverted, "Only owner should upgrade implementation";
}

invariant implementationNeverZero()
    implementation() != 0
    { preserved { require implementation() != 0; } }

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
