// AccessControl Specification - Land
// Hack: Sandbox_LAND
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: Land
// PRIVILEGED FUNCTION: burn
//

methods {
    // --- Privileged functions ---
    function burn(uint256 amount) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call burn ---
rule onlyOwnerCanCall_burn(env e, uint256 amount) {
    require e.msg.sender != currentContract.owner();
    burn@withrevert(e, amount);
    assert lastReverted, "Unprivileged caller should not be able to call burn";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
