// AccessControl Specification - NFT
// Hack: 88mph_NFT
// Auto-generated by validate_and_fix_dataset.py
// 2026-05-13 14:14 UTC
//
// CONTRACT: NFT
// PRIVILEGED FUNCTION: transferOwnership
//

methods {
    // --- Privileged functions ---
    function transferOwnership(address newOwner) external;
    function owner() external returns (address) envfree;
}

// --- Rule: only owner can call transferOwnership ---
rule onlyOwnerCanCall_transferOwnership(env e, address addr) {
    require e.msg.sender != currentContract.owner();
    transferOwnership@withrevert(e, addr);
    assert lastReverted, "Unprivileged caller should not be able to call transferOwnership";
}

// --- Invariant: zero address is never owner ---
invariant ownerNotZero()
    owner() != 0
    { preserved { require owner() != 0; } }
